### ISSUE TITLE
Xcode 8 and iOS 10 support

### ISSUE THREAD

**Issue by ecaselles** [indiegogo/KIF-Kiwi#10] opened 2016-11-07 12:21 UTC
I was wondering if there are any plans to update this library to support Xcode 8 and iOS 10. 

After a bit of investigation, I believe, in order to do so, the latest version of KIF (3.5) should be supported. Since it adds a new way to enable the accessibility inspector in Xcode 8 (see [#877](https://github.com/kif-framework/KIF/pull/877) and [#883](https://github.com/kif-framework/KIF/pull/883)).

This does not seem to execute when KIF tests are run using KIF-Kiwi, and I believe that is because the fix relies on the test spec being a subclass of `KIFTestCase`, so it can [enable accessibility on set up](https://github.com/kif-framework/KIF/blob/bcb58d0419cfaefe286f3df1c8618bac43b45921/Classes/KIFTestCase.m#L67).

I would be more than happy to help achieving this, but I would need a little help/guidance since I am not even sure where to start from.

**Comment by glentregoning** [comment] 2016-11-07 15:24
Thanks for raising this. Personally I have been able to get my KIF-Kiwi tests to run on the iOS 9.3 simulator on Xcode 8.x. So to clarify this appears to be an iOS 10 issue, more than Xcode 8 specifically. 

That said I haven't had a chance to look into why this doesn't work yet. It does seem accessibility related from what I can tell too. 

Unfortunately I don't have any suggestions on where to start here, but welcome your continued investigation and hopefully a PR. If I have some time I'll try investigate this more too.

**Comment by glentregoning** [comment] 2016-11-07 15:32
FYI I had a look into this issue and I believe the root cause is a change in the way iOS 10 enables accessibility labels. 

This appears to be a IOS10 / KIF incompatibility rather than a KIF-Kiwi issue. 

More information here on this (unfortunately closed but it resolved issue)
https://github.com/kif-framework/KIF/issues/897#issuecomment-2588667

There are a few proposed workarounds but no solution sadly.

**Comment by ecaselles** [comment] 2016-11-07 18:38
@glentregoning please check PR #11 we have just opened.

Yes, it is iOS 10 only and it relates to KIF-Kiwi because it uses Kiwi specs and these are based on `KWSpec` (subclass of `XCTestCase`). While the fix on KIF is done on their subclass of `XCTestCase`, `KIFTestCase`.

We have tackled the issue by adding the fix on an extension to the `KWSpec` to replicate the fix added in `KIFTestCase`.

**Comment by glentregoning** [comment] 2016-11-08 07:32
Thanks for your PR fixing this issue, I've merged it.

**Closed by glentregoning** 2016-11-08 07:32 UTC

**Comment by ecaselles** [comment] 2016-11-08 09:51
@glentregoning Thanks! 👍 🍷 🎩
